### ISSUE TITLE
Fix small bug

### ISSUE THREAD

**Issue by GFdevelop** [cxong/tinydir#32]
Tinydir disable pragma warning in all file that include this header, I have fixed the bug, update the repo:
before the line 41 add this:

`# pragma warning(push)`

before the last line ( last #endif ) add this;

```
#ifdef _MSC_VER
# pragma warning(pop)
#endif
```

Then pragma warning working in all files except tinydir.

**Comment by cxong** [comment]
Thanks; can you submit a PR?

**Comment by GFdevelop** [comment]
What is a PR?

**Comment by cxong** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by GFdevelop** [comment]
I'm going to sleep and I have shout down my notebook, tomotrow I send a pull request, sorry.
