### ISSUE TITLE
Not all Linux systems store PATH_MAX in linux/limits.h

### ISSUE THREAD

**Issue by seltzy** [cxong/tinydir#54]
I found this out while trying to compile on Alpine Linux, and I'm aware of a number of other distros like it. Systems that conform to POSIX (can't seem to find a clear reference to which standard) will keep it in the standard C limits.h - see comments [here](https://stackoverflow.com/questions/9449241/where-is-path-max-defined-in-linux#9449307). The [GNU docs](https://www.gnu.org/software/libc/manual/html_node/Limits-for-Files.html) also have some helpful notes on portability.

It's also worth noting that some implementations may have `PATH_MAX` include null-termination, and others may not. Not sure how you'd want to resolve that.

A more portable way to resolve this issue on POSIX 2001+ systems is to use [pathconf](https://linux.die.net/man/3/pathconf) as noted [here](https://stackoverflow.com/questions/833291/is-there-an-equivalent-to-winapis-max-path-under-linux-unix#833308).

**Comment by lautis0503** [comment]
We assume that PATH_MAX includes null-termination. In some special cases this would not be good, but it's safe. It seems difficult to figure out whether PATH_MAX includes null-termination or not.

**Comment by lautis0503** [comment]
Will including limits.h work for Alpine Linux?
It seems that [pathconf](https://linux.die.net/man/3/pathconf) will return _POSIX_PATH_MAX, which may not be the same with PATH_MAX in linux/limits.h. (Former is 1024 and latter is 4096 for me)
_POSIX_PATH_MAX should be the minimum values for path, but not the actual limit.
