### ISSUE TITLE
Error C2632: 'int' followed by 'int' is illegal  in windef.h file when trying to use the header file

### ISSUE THREAD

**Issue by bc0599** [cxong/tinydir#69]
Hello, I am new to C language. The error "C2632: 'int' followed by 'int' is illegal " points to windef.h	 line 153	1 when adding the header file to project.  I am using Microsoft Visual Studio 2010.

Any help will be very much appreciated.

**Comment by cxong** [comment]
Please show me your code

**Comment by lautis0503** [comment]
Close this issue since no information of the issue (if it is a issue) was provided.
